# Use a base image with Ubuntu 
FROM ubuntu:20.04

LABEL maintainer="azahir@pa.uc3m.es"

# Set environment variables to avoid user interaction during the installation
ENV DEBIAN_FRONTEND=noninteractive

# Install the required software-properties-common package
RUN apt-get update && \
    apt-get install -y software-properties-common \
    wget \
    iputils-ping \
    python3 \
    python3-pip \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
 
# Download and install specific version of Geth (1.13)
RUN wget https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.13.15-c5ba367e.tar.gz && \
    tar -xvf geth-linux-amd64-1.13.15-c5ba367e.tar.gz && \
    mv geth-linux-amd64-1.13.15-c5ba367e/geth /usr/local/bin/ && \
    rm -rf geth-linux-amd64-1.13.15-c5ba367e geth-linux-amd64-1.13.15-c5ba367e.tar.gz


# Add Ethereum PPA repository
RUN add-apt-repository -y ppa:ethereum/ethereum

# Update package list
RUN apt-get update

RUN pip3 install web3

# Install Ethereum package (bootnode)
RUN apt-get install -y bootnode

# Set the working directory inside the container
WORKDIR /src

# Copy the application code
# COPY src/ .