#!/usr/bin/env python3
"""
Capture the real (robot_hash, sidecar_hash, combined_hash) triplet from a
running attestation sidecar and write it into every ref-measurements/robot*.json
so that subsequent attestations can succeed against the real binary instead of
the placeholder hashes generated by create_agent_config.py.

All robots run the same target binary (robot_state_publisher or dummy_publisher)
and the same sidecar image, so a single sidecar's /digest is authoritative for
the whole fleet.

Usage:
    python3 bootstrap_ref_measurements.py --robots 4
    python3 bootstrap_ref_measurements.py --robots 4 --ref-dir ./ref-measurements-dummy
    python3 bootstrap_ref_measurements.py --robots 4 --sync-secaas

Sidecar /digest is exposed only on the optimized variant (start.sh
--contract optimized). Run AFTER start.sh has brought the fleet up.
"""
import argparse
import json
import os
import sys
import urllib.request


def fetch_digest(host: str, port: int, timeout: float = 10.0) -> dict:
    url = f"http://{host}:{port}/digest"
    with urllib.request.urlopen(url, timeout=timeout) as resp:
        body = resp.read().decode("utf-8")
    return json.loads(body)


def patch_ref_file(path: str, digest: dict) -> None:
    with open(path, "r") as f:
        data = json.load(f)
    data["robot_hash"] = digest["robot_hash"]
    data["attestation_sidecar_hash"] = digest.get("attestation_sidecar_hash", "")
    data["combined_hash"] = digest["combined_hash"]
    with open(path, "w") as f:
        json.dump(data, f, indent=4)


def sync_secaas(secaas_url: str, n_robots: int) -> None:
    url = f"{secaas_url}/sync-agents?n_robots={n_robots}"
    req = urllib.request.Request(url, method="POST",
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        print(resp.read().decode("utf-8"))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--robots", type=int, required=True,
                   help="Number of robots whose ref-measurements file to update")
    p.add_argument("--source-robot", type=int, default=1,
                   help="Robot index whose sidecar is queried (default: 1)")
    p.add_argument("--sidecar-host", default="localhost",
                   help="Sidecar host (default: localhost)")
    p.add_argument("--sidecar-port-base", type=int, default=8000,
                   help="Port = base + robot_index (default: 8000 -> robot1=8001)")
    p.add_argument("--ref-dir", default="./ref-measurements",
                   help="Directory holding robot{i}.json files (default: ./ref-measurements)")
    p.add_argument("--sync-secaas", action="store_true",
                   help="After patching, POST /sync-agents to SECaaS")
    p.add_argument("--secaas-url", default="http://localhost:8000",
                   help="SECaaS base URL (default: http://localhost:8000)")
    args = p.parse_args()

    port = args.sidecar_port_base + args.source_robot
    print(f"-> Querying sidecar at {args.sidecar_host}:{port}/digest ...")
    try:
        digest = fetch_digest(args.sidecar_host, port)
    except Exception as e:
        print(f"FAILED to fetch /digest: {e}", file=sys.stderr)
        return 1

    print(f"   robot_hash               = {digest['robot_hash']}")
    print(f"   attestation_sidecar_hash = {digest.get('attestation_sidecar_hash', '')}")
    print(f"   combined_hash            = {digest['combined_hash']}")
    if digest.get("libs_hash"):
        print(f"   libs_hash                = {digest['libs_hash']}")

    if not os.path.isdir(args.ref_dir):
        print(f"FAILED: ref dir not found: {args.ref_dir}", file=sys.stderr)
        return 1

    patched = 0
    for i in range(1, args.robots + 1):
        path = os.path.join(args.ref_dir, f"robot{i}.json")
        if not os.path.isfile(path):
            print(f"   skip (missing): {path}")
            continue
        patch_ref_file(path, digest)
        patched += 1
    print(f"-> Patched {patched}/{args.robots} files in {args.ref_dir}")

    if args.sync_secaas:
        print(f"-> Syncing SECaaS at {args.secaas_url} ...")
        try:
            sync_secaas(args.secaas_url, args.robots)
        except Exception as e:
            print(f"FAILED to sync SECaaS: {e}", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
