services:
  alpine1:
    image: alpine:3.20
    container_name: alpine1
    environment:
      MSG: "[alpine1] hello from container 1"
      INTERVAL: "3"
    command: >
      sh -c 'trap : TERM INT;
             while :; do
               echo "$(date -Iseconds) $$MSG";
               sleep "$${INTERVAL:-5}";
             done'
    restart: unless-stopped

  alpine2:
    image: alpine:3.20
    container_name: alpine2
    environment:
      MSG: "[alpine2] hello from container 2"
      INTERVAL: "4"
    command: >
      sh -c 'trap : TERM INT;
             while :; do
               echo "$(date -Iseconds) $$MSG";
               sleep "$${INTERVAL:-5}";
             done'
    restart: unless-stopped

  alpine3:
    image: alpine:3.20
    container_name: alpine3
    environment:
      MSG: "[alpine3] hello from container 3"
      INTERVAL: "5"
    command: >
      sh -c 'trap : TERM INT;
             while :; do
               echo "$(date -Iseconds) $$MSG";
               sleep "$${INTERVAL:-5}";
             done'
    restart: unless-stopped
