version: '3'
services:
  bootnode:
    image: dlt-node:geth-poa
    container_name: bootnode
    hostname: bootnode
    env_file: .env
    command: ./bootnode_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${BOOTNODE_IP}
    restart: always

  node1:
    image: dlt-node:geth-poa
    container_name: node1
    hostname: node1
    depends_on:
      - bootnode
    env_file: .env
    command: ./node1_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_1}
    restart: always

  node2:
    image: dlt-node:geth-poa
    container_name: node2
    hostname: node2
    depends_on:
      - bootnode
    env_file: .env
    command: ./node2_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_2}
    restart: always

  node3:
    image: dlt-node:geth-poa
    container_name: node3
    hostname: node3
    depends_on:
      - bootnode
    env_file: .env
    command: ./node3_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_3}
    restart: always

  node4:
    image: dlt-node:geth-poa
    container_name: node4
    hostname: node4
    depends_on:
      - bootnode
    env_file: .env
    command: ./node4_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_4}
    restart: always

  node5:
    image: dlt-node:geth-poa
    container_name: node5
    hostname: node5
    depends_on:
      - bootnode
    env_file: .env
    command: ./node5_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_5}
    restart: always

  node6:
    image: dlt-node:geth-poa
    container_name: node6
    hostname: node6
    depends_on:
      - bootnode
    env_file: .env
    command: ./node6_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_6}
    restart: always

  node7:
    image: dlt-node:geth-poa
    container_name: node7
    hostname: node7
    depends_on:
      - bootnode
    env_file: .env
    command: ./node7_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_7}
    restart: always

  node8:
    image: dlt-node:geth-poa
    container_name: node8
    hostname: node8
    depends_on:
      - bootnode
    env_file: .env
    command: ./node8_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_8}
    restart: always

  node9:
    image: dlt-node:geth-poa
    container_name: node9
    hostname: node9
    depends_on:
      - bootnode
    env_file: .env
    command: ./node9_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_9}
    restart: always

  node10:
    image: dlt-node:geth-poa
    container_name: node10
    hostname: node10
    depends_on:
      - bootnode
    env_file: .env
    command: ./node10_start.sh
    volumes:
      - "./config:/dlt-network/"
    networks:
      dlt_network:
        ipv4_address: ${IP_NODE_10}
    restart: always

  eth-netstats:
    image: eth-netstats
    container_name: eth-netstats
    depends_on:
      - node1
    ports:
      - "${ETH_NETSATS_PORT}:${ETH_NETSATS_PORT}"
    networks:
      dlt_network:
        ipv4_address: ${ETH_NETSATS_IP}
    restart: always

networks:
  dlt_network:
    name: dlt_network
    ipam:
      driver: default
      config:
        - subnet: ${DLT_SUBNET}
